from pathlib import Path

from querymind.export import export_sql_file, generate_javascript_snippet, generate_python_snippet


def test_export_sql_file(tmp_path: Path):
    target = tmp_path / "query.sql"
    sql = "SELECT id, name FROM customers WHERE country = 'DE'"
    export_sql_file(
        target,
        sql,
        question="customers from Germany",
        explanation="Filters customers by DE ISO country code.",
        assumptions=["Only active accounts included"],
    )

    assert target.is_file()
    content = target.read_text(encoding="utf-8")
    assert "Generated by QueryMind CLI" in content
    assert "Question: customers from Germany" in content
    assert "Explanation: Filters customers" in content
    assert "Assumptions: Only active accounts" in content
    assert "SELECT id, name FROM customers" in content


def test_generate_python_snippet():
    sql = "SELECT COUNT(*) FROM orders"
    py_code = generate_python_snippet(sql, host="127.0.0.1", port=3306, user="reader", db="shop")
    assert "import pymysql" in py_code
    assert 'HOST = os.getenv("QUERYMIND_DB_HOST", "127.0.0.1")' in py_code
    assert "SELECT COUNT(*) FROM orders" in py_code
    assert "cursor.execute(SQL)" in py_code


def test_generate_javascript_snippet():
    sql = "SELECT * FROM products LIMIT 10"
    js_code = generate_javascript_snippet(sql, host="127.0.0.1", port=3306, user="reader", db="shop")
    assert "require('mysql2/promise')" in js_code
    assert "SELECT * FROM products LIMIT 10" in js_code
    assert "connection.execute(sql)" in js_code
