"""Query and code snippet export for Python, JavaScript, and raw SQL."""

from __future__ import annotations

import datetime as dt
from pathlib import Path


def export_sql_file(
    path: Path,
    sql: str,
    question: str = "",
    explanation: str = "",
    assumptions: list[str] | None = None,
) -> Path:
    """Save query to a .sql file with rich metadata header comments."""
    now_str = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "-- -----------------------------------------------------------------------------",
        "-- Generated by QueryMind CLI",
        f"-- Date: {now_str}",
    ]
    if question:
        lines.append(f"-- Question: {question}")
    if explanation:
        lines.append(f"-- Explanation: {explanation}")
    if assumptions:
        lines.append(f"-- Assumptions: {'; '.join(assumptions)}")
    lines.append("-- -----------------------------------------------------------------------------")
    lines.append("")
    lines.append(sql.strip() + ";\n")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def generate_python_snippet(sql: str, host: str = "127.0.0.1", port: int = 3306, user: str = "qm_user", db: str = "shop") -> str:
    """Generate a clean, runnable Python script using pymysql to execute the query."""
    escaped_sql = sql.replace('"""', r'\"\"\"').strip()
    return f'''import os
import pymysql

# Database connection settings
HOST = os.getenv("QUERYMIND_DB_HOST", "{host}")
PORT = int(os.getenv("QUERYMIND_DB_PORT", {port}))
USER = os.getenv("QUERYMIND_DB_USER", "{user}")
PASSWORD = os.getenv("QUERYMIND_DB_PASSWORD", "")
DATABASE = os.getenv("QUERYMIND_DB_NAME", "{db}")

SQL = """{escaped_sql}"""

def main():
    conn = pymysql.connect(
        host=HOST,
        port=PORT,
        user=USER,
        password=PASSWORD,
        database=DATABASE,
        cursorclass=pymysql.cursors.DictCursor,
        autocommit=True,
    )
    try:
        with conn.cursor() as cursor:
            cursor.execute(SQL)
            results = cursor.fetchall()
            print(f"Fetched {{len(results)}} rows:")
            for row in results[:10]:
                print(row)
            if len(results) > 10:
                print(f"... and {{len(results) - 10}} more rows")
    finally:
        conn.close()

if __name__ == "__main__":
    main()
'''


def generate_javascript_snippet(sql: str, host: str = "127.0.0.1", port: int = 3306, user: str = "qm_user", db: str = "shop") -> str:
    """Generate a clean, runnable Node.js script using mysql2/promise to execute the query."""
    escaped_sql = sql.replace("`", r"\`").strip()
    return f'''const mysql = require('mysql2/promise');

async function main() {{
  const connection = await mysql.createConnection({{
    host: process.env.QUERYMIND_DB_HOST || '{host}',
    port: parseInt(process.env.QUERYMIND_DB_PORT || '{port}', 10),
    user: process.env.QUERYMIND_DB_USER || '{user}',
    password: process.env.QUERYMIND_DB_PASSWORD || '',
    database: process.env.QUERYMIND_DB_NAME || '{db}',
  }});

  const sql = `{escaped_sql}`;

  try {{
    const [rows, fields] = await connection.execute(sql);
    console.log(`Fetched ${{rows.length}} rows:`);
    console.table(rows.slice(0, 10));
    if (rows.length > 10) {{
      console.log(`... and ${{rows.length - 10}} more rows`);
    }}
  }} finally {{
    await connection.end();
  }}
}}

main().catch(console.error);
'''
